### ISSUE TITLE
TODO: Freelancer Profile Page

### ISSUE THREAD

**Issue by cuteolaf** [ImbueNetwork/imbue-frontend#124]
- [ ] Overview
  - [ ] Rating
  - [x] Share profile
  - [ ] Member Since
  - [x] Clients
    - [x] A tooltip needed
    - [x] A bug? Clicking a client (Fiverr, Imbue) removes it.    
    - [x] Adding a client    
       ![image](https://github.com/ImbueNetwork/imbue-frontend/assets/53915161/4f3f9a2d-b860-4cc1-92bb-415d84a5d91d)
       Should show a modal to add links 

  - [ ] Last Project Delivery
  - [ ] Number of projects
      ![image](https://github.com/ImbueNetwork/imbue-frontend/assets/53915161/5c4b2df1-9fd2-4786-83f8-959daf4be9df)
- [x] There should be a button to cancel edited changes
   ![image](https://github.com/ImbueNetwork/imbue-frontend/assets/53915161/4600fa2f-6d32-48f0-a9ca-a8ee01c6f375)

- [ ] Work History
- [ ] Client Reviews

**Comment by cuteolaf** [comment]
Remaining items will be resolved by the following issues.

https://github.com/ImbueNetwork/imbue-frontend/issues/150
https://github.com/ImbueNetwork/imbue-frontend/issues/151
https://github.com/ImbueNetwork/imbue-frontend/issues/152
https://github.com/ImbueNetwork/imbue-frontend/issues/153
https://github.com/ImbueNetwork/imbue-frontend/issues/154
https://github.com/ImbueNetwork/imbue-frontend/issues/155
